language: python
python:
  - '3.9'
env:
  - 'PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/py'

jobs:
  include:
    - language: python
      python: 3.9
      before_script:
        - cd $TRAVIS_BUILD_DIR/py
        - pip install --upgrade -r requirements/requirements.lock
      script:
        - bash scripts/lint.bash
        - bash scripts/mypy.bash
        - bash scripts/pytest.bash
    - language: rust
      rust: nightly
      before_script:
        - cd $TRAVIS_BUILD_DIR/rust/qtree
        - rustup component add clippy
      script:
        - cargo clippy
        - cargo build
        - cargo test -- --nocapture
