language: python
python:
  - '3.9'
env:
  - 'PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/py'

jobs:
  include:
    - language: python
      python: 3.9
      before_script:
        - cd $TRAVIS_BUILD_DIR/py && pip install --upgrade -r requirements/requirements.lock
      script:
        - bash scripts/ci.bash
    - language: rust
      rust: nightly
      before_script:
        - cd $TRAVIS_BUILD_DIR/rust/qtree && cargo build
      script:
        - cargo test -- --nocapture
