language: python
python:
  - '3.9'
env:
  - 'PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/py'
install:
  - cd py && pip install --upgrade -r requirements/requirements.lock
jobs:
  include:
    - stage: Lint
      name: Pylint
      script: bash scripts/lint.bash
    - stage: Typing
      name: Mypy
      script: bash scripts/pytest.bash
    - stage: Test
      name: Pytest
      script: pytest
